### ISSUE TITLE
please, publish for 0.6

### ISSUE THREAD

**Issue by antonkulaga** [benhutchison/prickle#11]
There will be anniversary of Scala-JS, please update and publish for stable 0.6 and inform here ( https://github.com/scala-js/scala-js-website/pull/114#issuecomment-72962689 )

**Comment by olivergg** [comment]
+1

**Comment by antonkulaga** [comment]
I've made a PR for MicroJSON https://github.com/benhutchison/MicroJson/pull/3 to move it to 0.6.0

**Comment by benhutchison** [comment]
Done
