### ISSUE TITLE
Failure(java.util.NoSuchElementException: None.get)

### ISSUE THREAD

**Issue by antonkulaga** [benhutchison/prickle#14]
Sometimes I get weird Failure(java.util.NoSuchElementException: None.get) errors. with a stacke trace like
```
scala.None$.get(Option.scala:347)
scala.None$.get(Option.scala:345)
prickle.CompositePickler.pickle(CompositePicklers.scala:23)
prickle.Pickle$.intoString(Pickler.scala:18)
org.scalax.prickling.PicklingSpec$$anonfun$tests$3$$anonfun$apply$3.apply(PicklingSpec.scala:93)
org.scalax.prickling.PicklingSpec$$anonfun$tests$3$$anonfun$apply$3.apply(PicklingSpec.scala:26)
```

I suspect something is wrong in CompositePickler, but I cannot provide a short case that fails yet

**Comment by benhutchison** [comment]
This indicates that a CompositePickler is being asked to unpickle a subclass it hasn't been told about. 

Note to self:  improve the error reporting here.

**Comment by benhutchison** [comment]
improved: https://github.com/benhutchison/prickle/commit/a37980b121cf10755b8ccff45fc620f27521bba5

**Comment by antonkulaga** [comment]
Thank you. Now it is much more clear as I originally suspected wrong pickling of Options=)
