### ISSUE TITLE
make composite and macro generated picklers compatible

### ISSUE THREAD

**Issue by antonkulaga** [benhutchison/prickle#15]
I think incompatibility between composite picklers and materialized picklers lead only to huge problems , confusion and waste of time. Please, make them compatible, I do not think that adding "cls" to materialized picklers is such a big sacrifice.

**Comment by benhutchison** [comment]
Can you precisely describe (with code) the situation where this would be useful? 

Non-composite Un/Picklers are used where the precise static type of the whole object graph is known. Composite picklers are used the precise static-type is not known, but the object is one of a finite set of subtypes.

Why are you not using the symmetrical unpickler to the pickler you used. What is the use case?

**Comment by antonkulaga** [comment]
I am moving my libs and apps from scala-js-pickling (that seems to be abandoned) to prickle and it is rather painful experience overrall. Sometimes even a small import import can break implicit resolution and materialization of prickle picklers. So I came to a point where I have a lot of explicitly materialized picklers (as I cannot rely on implicit materialization as it may brake whenever I import something that does any implicit conversion of any pickled types) and incompatibility between compound and materialized picklers forces me to have more pickers in my code then I would have in case of compatibility.
And overall having some compatibility is very natural. If you have a unpickler that produces Try[IRI] than it should work with IRIs pickled by composite (un)pickler that also produce IRIs. If the composite pickles for instance several other types, then there should be a warning about that and a nice error if it pickled BlankNode instead of IRI and you expected IRI. Not a criptic error about "cls" inside pickled string.

**Comment by benhutchison** [comment]
Compatibility between pickle formats of different picklers is not a goal for Prickle (except for between JVM and JS). User needs to unpickle with the same one that they pickled with.
