### ISSUE TITLE
Add Unit Pickler

### ISSUE THREAD

**Issue by cretz** [benhutchison/prickle#26]
E.g.

```scala
  implicit object UnitPickler extends Pickler[Unit] {
    def pickle[P](x: Unit, state: PickleState)(implicit config: PConfig[P]): P =
      config.makeNull()
  }
  
  implicit object UnitUnpickler extends Unpickler[Unit] {
    def unpickle[P](pickle: P, state: mutable.Map[String, Any])(implicit config: PConfig[P]) = Try(())
  }
```

**Comment by benhutchison** [comment]
Can you explain your use case? 

Won't Pickling then Unpickling a Unit by-name value (eg `=>print("Foo")`) with that code destroy whatever was previously there?

**Comment by cretz** [comment]
It's for return types of an Autowire service. Here's a bunch of links for one of my examples:

* API interface - https://github.com/cretz/scala-web-ideal/blob/1f45cb3d71f0f0690b6b551a8d1de16f45263c57/shared/src/main/scala/webideal/hangman/HangmanHandler.scala#L10, 
* Server impl - https://github.com/cretz/scala-web-ideal/blob/1f45cb3d71f0f0690b6b551a8d1de16f45263c57/server/src/main/scala/webideal/hangman/InSessionHangmanHandler.scala#L48
* Client call - https://github.com/cretz/scala-web-ideal/blob/1f45cb3d71f0f0690b6b551a8d1de16f45263c57/client/src/main/scala/webideal/hangman/HangmanJsImpl.scala#L124
* Prickle Autowire server support - https://github.com/cretz/scala-web-ideal/blob/1f45cb3d71f0f0690b6b551a8d1de16f45263c57/server/src/main/scala/webideal/util/PrickleAutowireSupport.scala
* Prickle Autowire client support - https://github.com/cretz/scala-web-ideal/blob/1f45cb3d71f0f0690b6b551a8d1de16f45263c57/client/src/main/scala/webideal/util/PrickleAutowireClient.scala
* Shared Prickle Autowire serializer support - https://github.com/cretz/scala-web-ideal/blob/1f45cb3d71f0f0690b6b551a8d1de16f45263c57/shared/src/main/scala/webideal/util/PrickleAutowireSerializers.scala
* Shared Prickle Unit data type support - https://github.com/cretz/scala-web-ideal/blob/1f45cb3d71f0f0690b6b551a8d1de16f45263c57/shared/src/main/scala/webideal/util/PrickleExtras.scala

Sorry for all the links, just figured it'd be easier than explaining how I'm using Prickle.
