### ISSUE TITLE
Diverging implicit expansion for Maps

### ISSUE THREAD

**Issue by tutnixzursache** [benhutchison/prickle#27]
Hi,

I get an error when I try to use Maps in the following way:

import prickle._
case class Bar(foos : Seq[Foo])
case class Foo(f : Map[String, Int] )
object T extends App{
  val bar = Bar(null)
  val barjson = Pickle.intoString(bar)
  println(barjson)
}

The error message:
[error] /home/tnzs/tmp/test/src/main/scala/test/T.scala:12: diverging implicit expansion for type prickle.Pickler[test.Bar]
[error] starting with method toPickler in object Pickler
[error] Error occurred in an application involving default arguments.
[error]   val barjson = Pickle.intoString(bar)

It compiles just fine if we for instance replace the Map[String,Int] with Seq[String]

Build.sbt:
name := "Foo"

scalaVersion := "2.11.7"

libraryDependencies += "com.github.benhutchison" %% "prickle" % "1.1.9"

**Comment by benhutchison** [comment]
Hi @tutnixzursache, appreciate the reproducible example.

Im going to offer you a workaround fix, but I don't understand the root cause (I cant get the compile to tell me why it's diverging there). Forcing the materialization of `Pickler[Foo]` gets it working:
```
import prickle._

case class Bar(foos : Seq[Foo])
case class Foo(f : Map[String, Int] )
object T extends App{
  implicit val fp = Pickler.materializePickler[Foo]
  val bar = Bar(null)
  val barjson = Pickle.intoString(bar)
  println(barjson)
}
```

**Comment by tutnixzursache** [comment]
Hi @benhutchison,

I poked a bit around in your code, however, I haven't found anything either.
Even '-Xlog-implicits' doesn't show anything useful...
Maybe its a compiler bug?

Nevetheless, your workaround also does its job for my actual code, thanks!
