### ISSUE TITLE
Is there any way to use prickle with standard json?

### ISSUE THREAD

**Issue by user471** [benhutchison/prickle#36]
```
case class Apple(isJuicy: Boolean)

val x = Unpickle[Seq[Apple]].fromString("[{isJuicy : false}]")
```
throw error

> Expected: field '#elems'  Actual: JsArray(Vector(JsObject(Map(isJuicy -> JsFalse)))))

**Comment by benhutchison** [comment]
Not really. Prickle is only intended to unpickle its own json format.
