### ISSUE TITLE
Unpickling an Seq in scala.js causes Error

### ISSUE THREAD

**Issue by Cedware** [benhutchison/prickle#40]
Pickle is unable tu Unpickle Json arrays on scala.js.
Take a look at this example:
```
case class Test(id: Int, name: String)
println(Unpickle[Test].fromString("""{id: 1, name: "test1"}"""))
println(Unpickle[Seq[Test]].fromString("""[{id: 1, name: "test1"},{id: 2, name: "test2"}]"""))
```
While the first Unpickle works fine the second on causes the following error:

> java.lang.RuntimeException: Expected: field '#elems'  Actual: JsArray(Vector(JsObject(Map(id -> JsNumber(1), name -> JsString(test1))), JsObject(Map(id -> JsNumber(2), name -> JsString(test2)))))

**Comment by benhutchison** [comment]
Please check the docs. Prickle only supports deserializing json emitted from the corresponding Pickler, not arbitrary json.
