### ISSUE TITLE
Can't unpickle Twitter's JSON

### ISSUE THREAD

**Issue by hmemcpy** [benhutchison/prickle#41]
Hello,

I have two objects that look like this:
```scala
case class User(name: String, screen_name: String, profile_image_url: String)
clase class Tweet(id: Long, text: String, user: User)
```
And a twitter response json (attached)

I'm trying to unpickle that into a `Seq[Tweet]`, like this:
```scala
Unpickle[Seq[Tweet]].fromString(json)
```

But I'm getting an exception:
```
 Expected: field '#elems'  Actual: JsArray(Vector(JsObject(Map(coordinates -> JsNull, retweeted -> 
 ...
```

Am I holding it wrong? Or do I need to do something to make this work?
Thanks!

[twitter-json.txt](https://github.com/benhutchison/prickle/files/949649/twitter-json.txt)

**Comment by benhutchison** [comment]
This isn't supported. Please check the docs. Prickle only supports deserializing json emitted from its corresponding Pickler, not arbitrary json such as Twitters
