### ISSUE TITLE
Support for Scala 2.13 and ScalaJS 1

### ISSUE THREAD

**Issue by lefou** [benhutchison/prickle#46]
Hi, are there any plans to support newer versions of Scala / Scala JS?

**Comment by benhutchison** [comment]
Very happy to. Are you using prickle and need support for them?

**Comment by lefou** [comment]
Great news! We're using prickle in https://github.com/woq-blended/blended and started to migrate to Scala 2.13. In than process we also wanted to change from ScalaJS 0.6 to 1.

**Comment by benhutchison** [comment]
Leave it with me. Should be out within 24 hours

**Comment by benhutchison** [comment]
Releasing now. But there's a catch. New version is only available for 2.13 / Scalajs 1.x, not 2.12

Reason is that some Scala collections redesign features (eg `Factory`) are not source compatible between 2.12 and 2.13 so migrating required dropping 2.12.

**Comment by lefou** [comment]
Will the serialized data still be compatible. E.g will it be possible to serialize from/to prickle 1.1.14 (with Scala 2.12 / Scala.js 0.6) and deserialize from/to 1.1.16 (with Scala 2.13 / Scala.js 1) ?
In that case we could keep the older version in the 2.12 tree.

**Comment by benhutchison** [comment]
I expect so. You'd need to test to be 100% sure but there were no format
changes.

**Comment by lefou** [comment]
Great, many thanks!
Oh, and is it possible to still publish for Scala.js 0.6(.32)?

**Comment by benhutchison** [comment]
Hi Tobias, I wont be cross-publishing for Scalajs 0.6x and 1.x off the
same Prickle version. There isnt good support for that in Scalajs.

**Comment by lefou** [comment]
Thank you for the follow up.
